Downgrade setuptools-scm (#4433)
Pin setuptools-scm to older version to prevent conflict with setuptools


>ERROR: setuptools==44.1.1 is used in combination with
setuptools-scm>=8.x